import {useEffect,useRef,useState} from "react";
const prices=[["Small & simple",400],["Medium tattoo",600],["Large tattoo",900],["Custom detailed piece",1200],["Half sleeve",1500],["Full sleeve",2500],["Back or chest piece",3000]] as const;
const sampleReviews=[["Maya R.","The consultation felt clear and comfortable from start to finish."],["Jordan K.","I loved how the design was shaped around my original idea."],["Alicia T.","The pricing and deposit information were easy to understand."],["Marcus D.","Quick answers and a very simple booking process."],["Nina S.","The fine line concept looked clean and personal."],["Chris B.","Friendly communication and thoughtful attention to detail."],["Taylor J.","The home service option made planning much easier."],["Sam P.","Professional guidance helped me choose the right placement."]] as const;
export default function App(){
 const [price,setPrice]=useState(400),[notice,setNotice]=useState(""),[open,setOpen]=useState(false),[cid,setCid]=useState(""),[replyAlert,setReplyAlert]=useState(""),[reviews,setReviews]=useState<{id:number;name:string;rating:number;comment:string}[]>([]),[reviewNotice,setReviewNotice]=useState("");
 const [messages,setMessages]=useState<{sender:string;body:string}[]>([{sender:"agent",body:"Welcome to Ink Noir. How can I help with your tattoo today?"}]); const input=useRef<HTMLInputElement>(null),agentCount=useRef(-1);
 useEffect(()=>{let id=localStorage.getItem("ink-noir-chat");if(!id){id=crypto.randomUUID();localStorage.setItem("ink-noir-chat",id)}setCid(id);const poll=async()=>{try{const r=await fetch(`/api/chat?conversationId=${encodeURIComponent(id!)}`);if(r.ok){const d=await r.json();if(d.messages?.length){const count=d.messages.filter((m:{sender:string})=>m.sender==="agent").length;if(agentCount.current>=0&&count>agentCount.current){setReplyAlert("New reply from the live agent. Tap to view.");setOpen(true);setTimeout(()=>setReplyAlert(""),8000)}agentCount.current=count;setMessages([{sender:"agent",body:"Welcome to Ink Noir. How can I help with your tattoo today?"},...d.messages])}}}catch{}};poll();const t=setInterval(poll,3000);return()=>clearInterval(t)},[]);
 useEffect(()=>{fetch("/api/reviews").then(r=>r.json()).then(d=>setReviews(d.reviews||[])).catch(()=>{})},[]);
 async function book(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setNotice("Sending your request...");const data={...Object.fromEntries(new FormData(e.currentTarget)),conversationId:cid};const r=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});if(r.ok){setNotice("Details submitted. Please wait for a reply.");e.currentTarget.reset();setOpen(true)}else setNotice("We could not send your request. Please check the details and try again.")}
 async function chat(e:React.FormEvent){e.preventDefault();const body=input.current?.value.trim();if(!body||!cid)return;setMessages(v=>[...v,{sender:"customer",body}]);if(input.current)input.current.value="";await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({conversationId:cid,body})})}
 async function submitReview(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setReviewNotice("Submitting...");const r=await fetch("/api/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});if(r.ok){const d=await r.json();setReviews(v=>[d.review,...v]);setReviewNotice("Thank you. Your review is now displayed.");e.currentTarget.reset()}else setReviewNotice("Please complete all review fields.")}
 return <main><div className="topbar">Now accepting appointments • 50% deposit secures every booking</div><header><nav className="wrap"><a className="brand" href="#top">INK<span>NOIR</span></a><div className="navlinks"><a href="#prices">Prices</a><a href="#process">How it works</a><a className="pill red" href="#book">Book now</a></div></nav></header>
 <section className="hero wrap" id="top"><div><p className="eyebrow">Custom tattoo experience</p><h1>WEAR YOUR <em>STORY.</em></h1><p className="lead">Original tattoos made for your skin, your style, and your story. No customer login required.</p><div className="actions"><a className="pill red" href="#book">Request appointment</a><a className="pill" href="#prices">View prices</a></div></div><div className="portrait"><img src="/artist.jpg?v=4" alt="Professional tattoo artist creating detailed black and grey artwork"/></div></section>
 <section id="prices"><div className="wrap"><div className="sectionHead"><h2>PRICES & DEPOSITS</h2><p>Every confirmed appointment requires a 50 percent deposit. The remaining half is due after the service. Final pricing may change based on size and detail.</p></div><div className="priceGrid">{prices.map(([name,p])=><article key={name}><div><h3>{name}</h3><p>Tattoo package</p></div><div className="priceAmount"><strong>Full price: ${p.toLocaleString()}</strong><span>Deposit: ${(p/2).toLocaleString()}</span></div></article>)}</div></div></section>
 <section id="process"><div className="wrap"><div className="sectionHead"><h2>BOOK WITH CONFIDENCE</h2><p>Your deposit confirms your booking and allows the artist to reserve your chosen time.</p></div><div className="steps"><article><b>01</b><h3>Send your details</h3><p>Share your name, number, tattoo idea, size, placement, date, and time.</p></article><article><b>02</b><h3>Choose payment</h3><p>Select the payment method you prefer for your deposit.</p></article><article><b>03</b><h3>Agent confirmation</h3><p>A live agent reviews your request and sends payment instructions.</p></article><article><b>04</b><h3>Pay 50 percent</h3><p>Pay half to secure your time. Never pay before an agent confirms.</p></article></div></div></section>
 <section className="reviewsSection" id="reviews"><div className="wrap"><div className="sectionHead"><h2>COMMUNITY REVIEWS</h2><p>{reviews.length} customer {reviews.length===1?"review":"reviews"} submitted. The moving examples below are clearly marked until more verified customer comments are received.</p></div></div><div className="reviewTrack">{[...sampleReviews,...sampleReviews].map(([name,comment],i)=><article key={i}><span>★★★★★</span><p>“{comment}”</p><b>{name}</b><small>Sample review</small></article>)}</div><div className="wrap reviewFormWrap"><div><h3>SHARE YOUR EXPERIENCE</h3><p>Real customer reviews appear here after submission.</p></div><form onSubmit={submitReview} className="reviewForm"><input name="name" required placeholder="Your name"/><select name="rating" required defaultValue="5"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><textarea name="comment" required placeholder="Write your review"></textarea><button type="submit">Post review</button><p>{reviewNotice}</p></form></div>{reviews.length>0&&<div className="wrap realReviews">{reviews.map(r=><article key={r.id}><span>{"★".repeat(r.rating)}</span><p>“{r.comment}”</p><b>{r.name}</b><small>Customer review</small></article>)}</div>}</section>
 <section className="booking" id="book"><div className="wrap"><div className="sectionHead"><h2>REQUEST YOUR APPOINTMENT</h2><p>Your details go directly to the admin inbox. A live agent will contact you after reviewing them.</p></div><form onSubmit={book} className="form"><label>Name<input name="name" required placeholder="Full name"/></label><label>Phone number<input name="phone" required placeholder="Working phone number"/></label><label className="full">Your location and address<input name="address" required autoComplete="street-address" placeholder="Street address, city, state and ZIP code"/></label><label>Tattoo package<select name="packageName" required value={price} onChange={e=>setPrice(Number(e.target.value))}>{prices.map(([n,p])=><option key={n} value={p}>{n} • from ${p.toLocaleString()}</option>)}</select></label><label>Deposit due<input value={`$${(price/2).toLocaleString()} (50%)`} readOnly/></label><label>Payment method<select name="paymentMethod" required defaultValue=""><option value="" disabled>Select payment method</option><option>Cash App</option><option>PayPal</option><option>Zelle</option><option>Apple Pay</option><option>Bank transfer</option><option>Other</option></select></label><label>Placement and size<input name="placement" required placeholder="Example: upper arm, 6 inches"/></label><label>Preferred date<input name="date" type="date" required/></label><label>Preferred time<input name="time" type="time" required/></label><label className="full">Tattoo idea<textarea name="idea" required placeholder="Describe your idea, colors, and references"/></label><input type="hidden" name="startingPrice" value={price}/><input type="hidden" name="deposit" value={price/2}/><button className="submit" type="submit">Send to live agent</button><p className="notice" role="status">{notice}</p></form></div></section>
 <footer><div className="wrap"><div className="footerTitle">INK<span>NOIR</span></div><p>Custom tattoos • By appointment • 50% deposit</p></div></footer>{replyAlert&&<button className="replyAlert" onClick={()=>{setOpen(true);setReplyAlert("")}}>{replyAlert}</button>}<button className="chatButton" onClick={()=>setOpen(v=>!v)}>{open?"×":"Chat with us"}</button>
 {open&&<aside className="chat"><div className="chatHead"><div><b>Live support</b><span>Replies appear here</span></div><button onClick={()=>setOpen(false)}>×</button></div><div className="chatBody">{messages.map((m,i)=><p key={i} className={m.sender}>{m.body}</p>)}</div><form onSubmit={chat}><input ref={input} placeholder="Type your message..." aria-label="Chat message"/><button>Send</button></form></aside>}</main>
}
